title: Automation Sandbox
description: Explainable self-healing UI test automation engine.
repository: mustafasercansak/automation-sandbox
markdown: kramdown

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - bin
  - obj
  - TestAutomation
  - WinFormsApp
  - WpfApp
  - samples
