<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>calibrate</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TestAutomation\UiModel\UiModel.csproj" />
    <ProjectReference Include="..\..\TestAutomation\SelfHealing\SelfHealing.csproj" />
  </ItemGroup>

</Project>
