using System;
using System.Collections.Generic;
using System.Text;

namespace WebDiscovery
{
    public static class PlaywrightLocatorEmitter
    {
        public static IReadOnlyList<PlaywrightLocatorSuggestion> Suggest(WebElementInfo element)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            var framePrefix = BuildFramePrefix(element.FrameAncestry);
            var suggestions = new List<PlaywrightLocatorSuggestion>();
            if (!string.IsNullOrWhiteSpace(element.TestId))
            {
                suggestions.Add(new PlaywrightLocatorSuggestion
                {
                    Strategy = "TestId",
                    Expression = $"{framePrefix}GetByTestId(\"{Escape(element.TestId)}\")",
                    Confidence = 0.98,
                    Reason = "data-testid is stable when owned by tests",
                });
            }

            if (!string.IsNullOrWhiteSpace(element.Role) && !string.IsNullOrWhiteSpace(element.AccessibleName))
            {
                suggestions.Add(new PlaywrightLocatorSuggestion
                {
                    Strategy = "Role",
                    Expression = $"{framePrefix}GetByRole(AriaRole.{ToAriaRole(element.Role)}, new() {{ Name = \"{Escape(element.AccessibleName)}\" }})",
                    Confidence = 0.90,
                    Reason = "role plus accessible name matches user-visible semantics",
                });
            }

            if (!string.IsNullOrWhiteSpace(element.Id))
            {
                suggestions.Add(new PlaywrightLocatorSuggestion
                {
                    Strategy = "Id",
                    Expression = $"{framePrefix}Locator(\"#{EscapeCssId(element.Id)}\")",
                    Confidence = 0.78,
                    Reason = "id is compact but can be generated by some frameworks",
                });
            }

            if (!string.IsNullOrWhiteSpace(element.NameAttribute))
            {
                suggestions.Add(new PlaywrightLocatorSuggestion
                {
                    Strategy = "NameAttribute",
                    Expression = $"{framePrefix}Locator(\"[name='{EscapeCssString(element.NameAttribute)}']\")",
                    Confidence = 0.70,
                    Reason = "name attribute is useful for form fields",
                });
            }

            if (!string.IsNullOrWhiteSpace(element.CssSelector))
            {
                suggestions.Add(new PlaywrightLocatorSuggestion
                {
                    Strategy = "Css",
                    Expression = $"{framePrefix}Locator(\"{Escape(element.CssSelector)}\")",
                    Confidence = 0.55,
                    Reason = "CSS selector is a fallback when semantic locators are unavailable",
                });
            }

            return suggestions;
        }

        private static string BuildFramePrefix(IReadOnlyList<string>? frameAncestry)
        {
            if (frameAncestry == null || frameAncestry.Count == 0)
            {
                return "page.";
            }

            var builder = new StringBuilder("page");
            foreach (var frame in frameAncestry)
            {
                if (!string.IsNullOrWhiteSpace(frame))
                {
                    builder.Append($".FrameLocator(\"{Escape(frame)}\")");
                }
            }
            builder.Append(".");
            return builder.ToString();
        }

        private static string ToAriaRole(string role)
        {
            var normalized = role.Replace("-", "").Replace("_", "");
            return normalized.Equals("textbox", StringComparison.OrdinalIgnoreCase)
                ? "Textbox"
                : char.ToUpperInvariant(normalized[0]) + normalized.Substring(1).ToLowerInvariant();
        }

        private static string Escape(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string EscapeCssId(string value)
        {
            return Escape(value.Replace(":", "\\:").Replace(".", "\\."));
        }

        private static string EscapeCssString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("'", "\\'");
        }
    }
}
