using System;
using System.Collections.Generic;
using System.Text;

namespace WebDiscovery
{
    public static class PlaywrightLocatorEmitter
    {
        public static IReadOnlyList<PlaywrightLocatorSuggestion> Suggest(WebElementInfo element)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            var framePrefix = BuildFramePrefix(element.FrameAncestry);
            var suggestions = new List<PlaywrightLocatorSuggestion>();
            if (!string.IsNullOrWhiteSpace(element.TestId))
            {
                suggestions.Add(new PlaywrightLocatorSuggestion
                {
                    Strategy = "TestId",
                    Expression = $"{framePrefix}GetByTestId(\"{EscapeCSharpString(element.TestId)}\")",
                    Confidence = 0.98,
                    Reason = "data-testid is stable when owned by tests",
                });
            }

            if (!string.IsNullOrWhiteSpace(element.Role) && !string.IsNullOrWhiteSpace(element.AccessibleName))
            {
                suggestions.Add(new PlaywrightLocatorSuggestion
                {
                    Strategy = "Role",
                    Expression = $"{framePrefix}GetByRole(AriaRole.{ToAriaRole(element.Role)}, new() {{ Name = \"{EscapeCSharpString(element.AccessibleName)}\" }})",
                    Confidence = 0.90,
                    Reason = "role plus accessible name matches user-visible semantics",
                });
            }

            if (!string.IsNullOrWhiteSpace(element.Id))
            {
                suggestions.Add(new PlaywrightLocatorSuggestion
                {
                    Strategy = "Id",
                    Expression = $"{framePrefix}Locator(\"#{EscapeCssId(element.Id)}\")",
                    Confidence = 0.78,
                    Reason = "id is compact but can be generated by some frameworks",
                });
            }

            if (!string.IsNullOrWhiteSpace(element.NameAttribute))
            {
                suggestions.Add(new PlaywrightLocatorSuggestion
                {
                    Strategy = "NameAttribute",
                    Expression = $"{framePrefix}Locator(\"[name='{EscapeCssString(element.NameAttribute)}']\")",
                    Confidence = 0.70,
                    Reason = "name attribute is useful for form fields",
                });
            }

            if (!string.IsNullOrWhiteSpace(element.CssSelector))
            {
                suggestions.Add(new PlaywrightLocatorSuggestion
                {
                    Strategy = "Css",
                    Expression = $"{framePrefix}Locator(\"{EscapeCSharpString(element.CssSelector)}\")",
                    Confidence = element.IsStructuralCssSelector ? 0.35 : 0.55,
                    Reason = element.IsStructuralCssSelector
                        ? "structural CSS selector is a last-resort fallback"
                        : "CSS selector is a fallback when semantic locators are unavailable",
                });
            }

            return suggestions;
        }

        private static string BuildFramePrefix(IReadOnlyList<string>? frameAncestry)
        {
            if (frameAncestry == null || frameAncestry.Count == 0)
            {
                return "page.";
            }

            var builder = new StringBuilder("page");
            foreach (var frame in frameAncestry)
            {
                if (!string.IsNullOrWhiteSpace(frame))
                {
                    builder.Append($".FrameLocator(\"{EscapeCSharpString(frame)}\")");
                }
            }
            builder.Append(".");
            return builder.ToString();
        }

        private static string ToAriaRole(string role)
        {
            var normalized = role.Replace("-", "").Replace("_", "");
            return normalized.Equals("textbox", StringComparison.OrdinalIgnoreCase)
                ? "Textbox"
                : char.ToUpperInvariant(normalized[0]) + normalized.Substring(1).ToLowerInvariant();
        }

        // These expressions are C# source consumed directly by PlaywrightCSharpTestGenerator.
        // This deliberately mirrors IntentAutomation.CodeGenerationUtilities rather than
        // referencing it: WebDiscovery is the lower-level dependency of IntentAutomation, so
        // calling upward would create a package cycle.
        private static string EscapeCSharpString(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t");
        }

        private static string EscapeCssId(string value)
        {
            // The DOM capture script delegates this operation to CSS.escape(). Mirroring the
            // CSSOM identifier serialization rules here keeps the independently emitted Id
            // strategy valid for every id the browser-derived Css strategy can represent.
            var escaped = new StringBuilder(value.Length);
            for (var index = 0; index < value.Length; index++)
            {
                var character = value[index];
                if (character == '\0')
                {
                    escaped.Append('\uFFFD');
                }
                else if ((character >= '\u0001' && character <= '\u001F')
                    || character == '\u007F'
                    || (index == 0 && character >= '0' && character <= '9')
                    || (index == 1 && character >= '0' && character <= '9' && value[0] == '-'))
                {
                    escaped.Append('\\');
                    escaped.Append(((int)character).ToString("x", System.Globalization.CultureInfo.InvariantCulture));
                    escaped.Append(' ');
                }
                else if (index == 0 && character == '-' && value.Length == 1)
                {
                    escaped.Append("\\-");
                }
                else if (character >= '\u0080'
                    || character == '-'
                    || character == '_'
                    || (character >= '0' && character <= '9')
                    || (character >= 'A' && character <= 'Z')
                    || (character >= 'a' && character <= 'z'))
                {
                    escaped.Append(character);
                }
                else
                {
                    escaped.Append('\\');
                    escaped.Append(character);
                }
            }

            return EscapeCSharpString(escaped.ToString());
        }

        private static string EscapeCssString(string value)
        {
            // First encode the value for a single-quoted CSS attribute string. Then encode
            // that complete selector fragment for the surrounding C# string literal. Keeping
            // these layers separate is what preserves the CSS backslash at runtime.
            var cssString = value
                .Replace("\\", "\\\\")
                .Replace("'", "\\'")
                .Replace("\r", "\\D ")
                .Replace("\n", "\\A ")
                .Replace("\t", "\\9 ");
            return EscapeCSharpString(cssString);
        }
    }
}
